server:
  port: 9000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8080/
          predicates:
            - Path=/product/**
        - id: cart-service
          uri: http://localhost:8081/
          predicates:
            - Path=/cart/**
        - id: auth-service
          uri: http://localhost:9100/
          predicates:
            - Path=/auth/**